location: ENC[AES256_GCM,data:KLmk/lZ1MRV321OY4JIcOsVC1yw=,iv:DOGeAxGb6UhffeDbliTQBhJUqs0W2GAABUJBgVJqwPo=,tag:/xCjYr2nd/aKrBjwmbMhgA==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE3vgTYeAKBwpOt6o3E7IBOvusIYcR8GcaE/y2KffaQJ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFJTUGJZdyA2Z3RG
            U1hqV0NiVTd1MU81cEFrZCtMbE9iUll0Unhva2I4T3crdFlGOUhVCms3bEtrOWlR
            RThZL3htK1hpWHdkRDBvWTlWclkybVhhWjhjNW9VWUx0dXcKLS0tIFIrTVFpTERG
            eUFKRHdhdUdkWDFoc3RBaFhSUGF1SmhHckRFek5uTVJtUWsK1+pdWd2ovlpdovVN
            SI1F67KNSqgSlOOhdaMct/F9IQ23c1n4BtjlYBKmY1IsHu6BJmHFaORb0XVcWqvR
            AdcCOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T18:05:58Z"
    mac: ENC[AES256_GCM,data:mfCC/p/ocnqpeL5NAT71Np8sd6TwVKv3xCBxSoqrXYDvSZMTKY/0n4urnzySp0nOnjPJH1Lw4O9sim9b1GLz4cHo54xlgpGJeUweKQK8Z5mCHxHq9KmQ0TY+wfbv6Anern8iBhoZccXIZ5fRJ+mQJXwUnqYtmKlI98AcR7Z189s=,iv:xVHzDp0NR1lnFoXVXGsZJ6I9vX9oMQ1phOfFUP6w4/g=,tag:64JltcS4bgdRbmT1DZexMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
